objtype=power
</$objtype/mkfile
CPU=mips 386 alpha power
CFLAGS=-FVw
ALFLAGS=-w

LIB=/$objtype/lib/alef/libA.a

AFILES=frexp.l\
	lock.l\
	nan.l\

SFILES =alefasm.s\
	getfcr.s\
	main9.s\
	memccpy.s\
	memchr.s\
	memcmp.s\
	memmove.s\
	memset.s\
	strchr.s\
	strcmp.s\
	strcpy.s\

HFILES=run.h

<../rt/mkfile
